# see https://github.com/marketplace/actions/intellij-plugin-verifier
name: Plugin compatibility
on: [ push, pull_request ]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]
    steps:
      - uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build the plugin using Gradle
        run: ./gradlew buildPlugin -PdownloadIdeaSources=false --warning-mode all
      - uses: thepieterdc/intellij-plugin-verifier-action@v1.2.0
        with:
          plugin: '/home/runner/work/intellij-extra-icons-plugin/intellij-extra-icons-plugin/build/distributions/*'
          versions: |
            2020.1.4
            2020.2.1
